nome= input ('Qual é seu nome?')
print ('Olá {}, seja bem vindo ao meu programa!'.format(nome))
n = input('Digite algo:')
print ('Ele é um número booiliano?')
print (n.isnumeric())
print ('Ele é uma letra?')
print (n.isalpha())
print ('Ele é alfanumerico?')
print(n.isalnum())
print ('Ele contém apenas letras maiusculas?')
print(n.isupper())
print ('Obrigado {}, pelo desafio!'.format(nome))